### ISSUE TITLE
[bug] Copy, cut and paste are off screen in portrait mode when renaming a file

### ISSUE THREAD

**Issue by danielmmmm** [DF1E/SimpleExplorer#32] opened 2015-02-09 13:22 UTC
When I rename a file and long-click onto the file name to copy, cut or paste text, I only see a check mark on the left top. Only when I rotate into landscape mode do I see the label "Text selection" next to the check mark, and the buttons "SELECT ALL", "CUT", "COPY" and "PASTE".

**Comment by unrulygnu** [comment] 2015-05-09 23:59
Confirmed in Jelly Bean:

**Device and Software**
* Google Galaxy Nexus
* Android 4.2.2 JDQ39 stock; root
* Simple Explorer 2.2.5

![Uploading SimpleExplorer-2.2.5-issue-contextualactionbar-copytext-android4.2.2.png…]()

Note that this issue does not arise on a Nexus 5 running Lollipop (Android 5.1):

![Uploading SimpleExplorer-2.2.5-issue-contextualactionbar-copytext-android5.1.png…]()

**Comment by unrulygnu** [comment] 2015-05-10 19:19
`Theme.AppCompat` uses all white drawables for `ActionMenu` item icons; there are no light/dark themed versions.  It's likely that they are supposed to be colored at runtime using the new drawable tinting support.

In versions 22.1.0 and 22.1.1,  `ActionMode` theming seems to be incomplete, using the local platform theme along with the untinted, white `AppCompat` drawable icons.  Further, it seems that the only `ActionMode`attributes respected in a child theme are the icon drawables themselves (`actionModeSelectAllDrawable`, `actionModeCutDrawable`, `actionModeCopyDrawable`, `actionModePasteDrawable`).  This is from trial and error, not from a deep code dive, so there may be others that are respected.

Although the new `android.support.v7.AlertDialog` properly tints the `ActionMode` drawables, the  `ActionMode` is broken and unusable at this point, both on Jelly Bean and on Lollipop.  Once it is fixed, implementing `android.support.v7.AlertDialog` will probably be the best long-term fix for this issue.

In the interim, light/dark drawables could be assigned to the theme attributes above.  At the very least, a new paste drawable would need to be added to the project; however, since the `android.support.v7.AlertDialog` implements Material icons, it would probably be best to add the full set of these for consistency.

@DF1E , what do you think?

**Closed** 2015-05-12 15:01 UTC

**Comment by DF1E** [comment] 2015-05-12 15:02
thanks for your pull request. I couldnt fix it because I couldnt reproduce it on cyanogenmod

**Comment by danielmmmm** [comment] 2015-05-15 15:41
Hm, too bad that you couldn't fix it. I am using CyanogenMod 11 M12.

**Comment by unrulygnu** [comment] 2015-05-15 21:12
@danielmmmm , my pull request with an interim fix (tested on stock 4.2.2) was merged into master.  If you clone the source and build it, I'd look forward to your feedback.

**Comment by danielmmmm** [comment] 2015-05-16 13:34
Since I am not a programmer (unfortunately!), I will have to wait for the next F-Droid release. I will report back, once I get the chance to test :-)
